if has('win32')
    set guifont=Hack_Nerd_Font_Mono:h12,Consolas:h12
    set guifontwide=MS_Gothic:h12
    set linespace=0
    set renderoptions=type:directx,geom:1,renmode:5,taamode:1

    augroup gvimrc
        autocmd!
        autocmd GUIEnter * simalt ~x
    augroup END
endif

set columns=160
set lines=48
