if has('win32')
    set guifont=Hack_Nerd_Font_Mono:h11,Consolas:h11
    set guifontwide=MS_Gothic:h11
    set linespace=0
    set renderoptions=type:directx,geom:1,renmode:5,taamode:1
endif

set columns=200
set lines=50
