" initialization
scriptversion 4
syntax enable
filetype plugin indent on

" options
set autoindent
set autoread
set backupdir=$MYVIMDIR/backup
set belloff=all
set clipboard=unnamed
set cmdheight=2
set completeopt=menuone,longest,preview
set diffopt^=vertical
set directory=$MYVIMDIR/swap
set display=lastline
set expandtab
set fileformats=unix,dos
set fillchars=vert:│,fold:─,foldopen:󰍝,foldclose:󰍟,foldsep:│,diff:─,eob:󰜥,lastline:
set formatoptions+=mM
set hidden
set history=10000
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set lazyredraw
set list
set listchars=tab:󰅂─,leadmultispace:\ \ \ │,trail:󱓼,extends:󰄾,precedes:󰄽,conceal:
set nrformats-=octal
set number
set relativenumber
set ruler
set scrolloff=5
set shiftwidth=4
set shortmess+=a
set showcmd
set showmatch
set sidescrolloff=5
set signcolumn=yes
set smartcase
set smartindent
set smarttab
set softtabstop=-1
set spelllang=en,cjk
set spelloptions=camel
set splitbelow
set splitright
set statusline=%<%f\ %y%m%r%h%w%q%{'['.(&fileencoding!=''?&fileencoding:&encoding).']['.&fileformat.']'}%=%p%%\ [Ln:%l/%L\ Cl:%v]
set noswapfile
set ttimeout
set ttimeoutlen=100
set undodir=$MYVIMDIR/undo
set undofile
set updatetime=300
set viewdir=$MYVIMDIR/view
set viminfofile=$MYVIMDIR/viminfo
set virtualedit=block
set whichwrap+=<,>,~,[,]
set wildignorecase
set wildmode=longest:full,full
set wildoptions=fuzzy,pum,tagfile
set nowritebackup

let &showbreak = '󱞪   '

if executable('rg')
    set grepformat=%f:%l:%c:%m
    set grepprg=rg\ --vimgrep
endif

if exists('+termguicolors')
    set termguicolors
endif

if has('vim_starting')
    let &t_SI ..= "\e[6 q"
    let &t_EI ..= "\e[2 q"
    let &t_SR ..= "\e[4 q"
endif

if has('win32')
    set completeslash=slash
endif

try
    set completeopt+=fuzzy
catch
endtry

" autocmds
augroup vimrc
    autocmd!
    autocmd BufNewFile,BufRead *.ahk,*.bat,*.cmd,*.ps1,*.reg,*.vb,*.vbs setlocal fileformat=dos fileencoding=cp932 completeslash=backslash
    autocmd BufNewFile,BufRead gitconfig,.gitconfig,*/git/config,*/.git/config setlocal tabstop=4 noexpandtab
    autocmd FileType,BufRead dbout,fugitive,help,qf nnoremap <silent><buffer> q :<C-u>quit<CR>
    autocmd FileType,BufRead html,markdown,txt setlocal spell
    autocmd FileType,BufRead aichat execute 'setlocal wrap | nnoremap <silent><buffer> <Leader>a :<C-u>AIChat<CR>'
augroup END

" commands
command! -nargs=* Grep silent grep <args> | cwindow

command! Note silent execute 'edit ' .. expand(strftime('~/Documents/Notes/%Y-%m/%Y-%m-%d.md'))

" keymaps
let g:mapleader = ','
let g:maplocalleader = ' '

map n nzz
map N Nzz
map Y y$

map! <C-a> <Home>
map! <C-b> <Left>
map! <C-d> <Del>
map! <C-e> <End>
map! <C-f> <Right>
map! <C-n> <Down>
map! <C-p> <Up>

nmap <silent> <Esc><Esc> :<C-u>nohlsearch<CR>

nmap <silent> b$ :<C-u>blast<CR>
nmap <silent> b0 :<C-u>bfirst<CR>
nmap <silent> bd :<C-u>bdelete<CR>
nmap <silent> bn :<C-u>bnext<CR>
nmap <silent> bp :<C-u>bprevious<CR>

nmap <silent> t$ :<C-u>tablast<CR>
nmap <silent> t0 :<C-u>tabfirst<CR>
nmap <silent> td :<C-u>tabclose<CR>
nmap <silent> th :<C-u>tabmove -<CR>
nmap <silent> tl :<C-u>tabmove +<CR>
nmap <silent> tn :<C-u>tabnext<CR>
nmap <silent> tp :<C-u>tabprevious<CR>

if has('win32') && executable('powershell')
    nmap <silent> <Leader>sh :<C-u>vertical terminal powershell<CR>
else
    nmap <silent> <Leader>sh :<C-u>vertical terminal<CR>
endif

" plugins
let g:loaded_2html_plugin = 1
let g:loaded_getscriptPlugin = 1
let g:loaded_logiPat = 1
let g:loaded_manpager_plugin = 1
let g:loaded_netrw = 1 | let g:loaded_netrwPlugin = 1
let g:loaded_tutor_mode_plugin = 1
let g:loaded_vimballPlugin = 1

function! s:LoadPlugins(timer)
    packadd comment
    packadd hlyank
    packadd nohlsearch
    packadd! editorconfig
    packadd! matchit

    let l:vimplug = expand($MYVIMDIR .. '/autoload/plug.vim')

    if !filereadable(l:vimplug)
        if executable('curl')
            call system('curl -fLo ' .. shellescape(l:vimplug) .. ' --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim')
        endif

        if !filereadable(l:vimplug)
            echoerr 'Please install the vim-plug manually. You can download it from https://github.com/junegunn/vim-plug and put it in ' .. l:vimplug

            finish
        endif
    endif

    if executable('git') && plug#begin('~/.local/vim/plugin')
        " ale
        let g:ale_completion_enabled = 1
        let g:ale_linters = {
                    \ 'markdown': [ 'textlint' ],
                    \ 'text': [ 'textlint' ],
                    \ }

        " coc.nvim
        let g:coc_data_home = '~/.local/vim/coc'
        let g:coc_global_extensions = [
                    \ 'coc-snippets',
                    \ 'coc-markdown-preview-enhanced', 'coc-webview',
                    \ 'coc-vimlsp',
                    \ 'coc-json', 'coc-toml', 'coc-xml', 'coc-yaml',
                    \ 'coc-html', 'coc-css',
                    \ 'coc-tsserver', 'coc-eslint', 'coc-prettier',
                    \ 'coc-prisma', '@yaegassy/coc-volar',
                    \ ]

        if executable('clangd')
            call add(g:coc_global_extensions, 'coc-clangd')
        endif

        if executable('cmake')
            call add(g:coc_global_extensions, 'coc-cmake')
        endif

        if executable('docker')
            call add(g:coc_global_extensions, 'coc-docker')
        endif

        if executable('dotnet')
            call add(g:coc_global_extensions, 'coc-omnisharp')
        endif

        if executable('go')
            call add(g:coc_global_extensions, 'coc-go')
        endif

        if executable('javac')
            call add(g:coc_global_extensions, 'coc-java')
        endif

        if executable('lua') || executable('luajit')
            call add(g:coc_global_extensions, 'coc-lua')
        endif

        if executable('perl')
            call add(g:coc_global_extensions, 'coc-perl')
        endif

        if executable('php')
            call extend(g:coc_global_extensions, [
                        \ 'coc-phpls', 'coc-phpactor', 'coc-php-cs-fixer', '@yaegassy/coc-phpstan',
                        \ '@yaegassy/coc-laravel', 'coc-blade',
                        \ ])
        endif

        if executable('python3') || executable('python')
            call extend(g:coc_global_extensions, [ 'coc-pyright', 'coc-pydocstring' ])
        endif

        if executable('ruby')
            call add(g:coc_global_extensions, 'coc-solargraph')
        endif

        if executable('rustc')
            call add(g:coc_global_extensions, 'coc-rust-analyzer')
        endif

        if executable('sqlite3') || executable('psql') || executable('mysql')
            call add(g:coc_global_extensions, 'coc-sql')
        endif

        " fzf
        let g:fzf_action = { 'Ctrl-t': 'tab split', 'Ctrl-i': 'split', 'Ctrl-s': 'vsplit' }
        let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6 } }

        " nerdtree
        let g:NERDTreeBookmarksFile = $MYVIMDIR .. '/NERDTreeBookmarks'
        let g:NERDTreeGitStatusUseNerdFonts = 1
        let g:NERDTreeIgnore = [ '\~$', '\.git$' ]
        let g:NERDTreeShowHidden = 1
        let g:NERDTreeWinSize = 30

        " vim-ai
        let g:vim_ai_chat = {
                    \ 'options': {
                    \   'model': 'gpt-4.1-mini',
                    \   'selection_boundary': '```',
                    \   },
                    \ }
        let g:vim_ai_complete = {
                    \ 'options': {
                    \   'model': 'gpt-4.1-mini',
                    \   },
                    \ }
        let g:vim_ai_edit = {
                    \ 'options': {
                    \   'model': 'gpt-4.1-mini',
                    \   },
                    \ }
        let g:vim_ai_chat_markdown = 1
        let g:vim_ai_token_file_path = expand('~/.config/openai.token')
        let l:vim_ai_roles_config_file = expand($MYVIMDIR .. '/roles.ini')

        if filereadable(expand($MYVIMDIR .. '/roles.ini'))
            let g:vim_ai_roles_config_file = expand($MYVIMDIR .. '/roles.ini')
        endif

        unlet l:vim_ai_roles_config_file

        " vim-airline
        let g:airline_extensions = [
                    \ 'ale',
                    \ 'branch',
                    \ 'coc',
                    \ 'fugitiveline',
                    \ 'fzf',
                    \ 'obsession',
                    \ 'quickfix',
                    \ 'scrollbar',
                    \ 'tabline',
                    \ 'term',
                    \ 'whitespace',
                    \ ]
        let g:airline_experimental = 1
        let g:airline_powerline_fonts = 1
        let g:airline_left_sep = ''
        let g:airline_right_sep = ''
        let g:airline_left_alt_sep = ''
        let g:airline_right_alt_sep = ''

        if !exists('g:airline_symbols')
            let g:airline_symbols = {}
        endif

        let g:airline_symbols.linenr = ' '
        let g:airline_symbols.maxlinenr = ''
        let g:airline_symbols.colnr = ':'
        let g:airline_symbols.branch = '󰘬'
        let g:airline_symbols.paste = '󰆒 Paste'
        let g:airline_symbols.readonly = '󰑇 Readonly'
        let g:airline_symbols.spell = '󰓆 Spell'
        let g:airline_symbols.crypt = '󰌾 Crypt'
        let g:airline_symbols.dirty = ' 󱐋'
        let g:airline_symbols.notexists = ' 󱥸'
        let g:airline_symbols.whitespace = '󱗽󱞥'

        let g:airline#extensions#ale#error_symbol = '󰅖 Error:'
        let g:airline#extensions#ale#warning_symbol = '󰈅 Warning:'
        let g:airline#extensions#coc#error_symbol = g:airline#extensions#ale#error_symbol
        let g:airline#extensions#coc#warning_symbol = g:airline#extensions#ale#warning_symbol
        let g:airline#extensions#obsession#indicator_text = ' Session'

        " vim-devicons
        let g:webdevicons_enable_unite = 0
        let g:webdevicons_enable_vimfiler = 0
        let g:webdevicons_enable_ctrlp = 0
        let g:webdevicons_enable_startify = 0
        let g:webdevicons_enable_flagship_statusline = 0
        let g:webdevicons_enable_denite = 0

        if !exists('g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols')
            let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {}
        endif

        let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols[ 'vue' ] = '󰡄'

        " vim-polyglot
        let g:polyglot_disabled = [
                    \ 'autoindent',
                    \ 'sensible',
                    \ 'ftdetect',
                    \ ]

        " Plugs
        Plug 'airblade/vim-gitgutter'
        Plug 'easymotion/vim-easymotion'
        Plug 'github/copilot.vim'
        Plug 'jiangmiao/auto-pairs'
        Plug 'preservim/nerdtree' | Plug 'Xuyuanp/nerdtree-git-plugin' |
                    \ if !has('win32') |
                    \   Plug 'tiagofumo/vim-nerdtree-syntax-highlight' |
                    \   endif
        Plug 'joshdick/onedark.vim'
        Plug 'sheerun/vim-polyglot'
        Plug 'tpope/vim-endwise'
        Plug 'tpope/vim-fugitive'
        Plug 'tpope/vim-obsession'
        Plug 'tpope/vim-repeat'
        Plug 'tpope/vim-surround'

        if executable('fzf')
            Plug 'junegunn/fzf' | Plug 'junegunn/fzf.vim'
        endif

        if executable('node')
            Plug 'dense-analysis/ale'
            Plug 'neoclide/coc.nvim', { 'branch': 'release' } | Plug 'honza/vim-snippets'
        endif

        if has('python3')
            Plug 'madox2/vim-ai'
        endif

        Plug 'vim-airline/vim-airline'

        if !has('win32')
            Plug 'ryanoasis/vim-devicons'
        endif

        call plug#end()

        for l:key in keys(g:plugs)
            if !isdirectory(expand(g:plugs[ l:key ].dir .. '/.git'))
                echomsg 'Please wait for a while to complete the installation.'

                PlugInstall --sync

                break
            endif
        endfor
    endif

    " coc.nvim
    if exists(':CocStart')
        CocStart

        autocmd vimrc CursorHold * silent call CocActionAsync('highlight')

        command! -nargs=0 Format :call CocActionAsync('format')
        command! -nargs=? Fold :call CocAction('fold', <f-args>)
        command! -nargs=0 OR :call CocActionAsync('runCommand', 'editor.action.organizeImport')
        command! -nargs=0 OpenLink :call CocAction('openLink')
        command! -nargs=0 OpenPreview :call CocActionAsync('runCommand', 'markdown-preview-enhanced.openPreview')

        function! s:ShowDocumentation()
            if CocAction('hasProvider', 'hover')
                call CocActionAsync('doHover')
            else
                call feedkeys('K', 'in')
            endif
        endfunction

        inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                    \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

        nnoremap <silent> K :call <SID>ShowDocumentation()<CR>

        nmap <silent><nowait> gd <Plug>(coc-definition)
        nmap <silent><nowait> gy <Plug>(coc-type-definition)
        nmap <silent><nowait> gi <Plug>(coc-implementation)
        nmap <silent><nowait> gr <Plug>(coc-references)

        nmap <Leader>rn <Plug>(coc-rename)

        xmap <Leader>f <Plug>(coc-format-selected)

        nmap <Leader>a <Plug>(coc-codeaction-selected)
        xmap <Leader>a <Plug>(coc-codeaction-selected)

        nmap <Leader>qf <Plug>(coc-fix-current)

        nmap <silent> <leader>r <Plug>(coc-codeaction-refactor)
        xmap <silent> <leader>r <Plug>(coc-codeaction-refactor-selected)

        if has('nvim-0.4.0') || has('patch-8.2.0750')
            nnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
            nnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
            inoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(1)\<cr>" : "\<Right>"
            inoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(0)\<cr>" : "\<Left>"
            vnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
            vnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
        endif

        let g:coc_snippet_next = '<C-j>'
        let g:coc_snippet_prev = '<C-k>'

        imap <C-l> <Plug>(coc-snippets-expand)
        vmap <C-j> <Plug>(coc-snippets-select)
        imap <C-j> <Plug>(coc-snippets-expand-jump)
        xmap <leader>x  <Plug>(coc-convert-snippet)
    endif

    " fzf
    if exists(':Files')
        if !exists('$FZF_DEFAULT_COMMAND')
            if executable('fd')
                let $FZF_DEFAULT_COMMAND = 'fd --hidden --follow --type f'
            elseif executable('rg')
                let $FZF_DEFAULT_COMMAND = 'rg --hidden --follow --files'
            endif

            let $FZF_DEFAULT_OPTS = '--height 40% --layout=reverse --preview "bat --color=always {}"'
        endif

        nmap <silent> <Leader>f :<C-u>Files<CR>
        nmap <silent> <Leader>g :<C-u>GFiles<CR>
        nmap <silent> <Leader>b :<C-u>Buffers<CR>
        nmap <silent> <Leader>w :<C-u>Windows<CR>
    endif

    " nerdtree
    if exists(':NERDTree')
        nnoremap <silent> <Leader>e :<C-u>NERDTreeFocus<CR>
    endif

    " onedark
    let l:colors_name = 'onedark'

    if !empty(getcompletion(l:colors_name, 'color'))
        set background=dark

        execute 'colorscheme ' .. l:colors_name

        let g:airline_theme = l:colors_name
    endif

    unlet l:colors_name

    " vim-ai
    if exists(':AINewChat')
        delcommand AINewChat
    endif

    " vim-devicons
    if !exists('*WebDevIconsGetFileTypeSymbol')
        let g:NERDTreeGitStatusConcealBrackets = 1
    endif
endfunction

if has('gui_running')
    autocmd vimrc GUIEnter * call timer_start(10, function('s:LoadPlugins'))
else
    call timer_start(10, function('s:LoadPlugins'))
endif
