version: 2

root-markers:
  - .git

lint-debounce: 1s

tools:
  textlint: &textlint
    lint-command: 'textlint --format unix ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'
    root-markers:
      - .textlintrc

languages:
  markdown:
    - <<: *textlint

  text:
    - <<: *textlint
